apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llmops-fastapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Himanshu9001/LLMOps-Bedrocks-Project.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: llmops
  syncPolicy:
    automated:
      prune: true      # delete resources removed from Git
      selfHeal: true   # revert manual kubectl changes automatically
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
