apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-sa
  namespace: llmops
  annotations:
    # IRSA — pod assumes this IAM role via projected service account token
    eks.amazonaws.com/role-arn: arn:aws:iam::011528270076:role/llmops-bedrock-dev-fastapi-irsa-role